// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7OxVUHqfg9Ka1kpM5uGKeiY512Rf48G8',
    appId: '1:758888854246:web:dc22badde1726681dd0127',
    messagingSenderId: '758888854246',
    projectId: 'cyphlab',
    authDomain: 'cyphlab.firebaseapp.com',
    storageBucket: 'cyphlab.firebasestorage.app',
    measurementId: 'G-471EBXFXNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjlzvyoUiY5-G7TQMPKEZ7oJKzAAkOUXs',
    appId: '1:758888854246:android:3ac896fb9c5d3423dd0127',
    messagingSenderId: '758888854246',
    projectId: 'cyphlab',
    storageBucket: 'cyphlab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0dTo66Ytj4u9EnBFD7yZh8C7al5DbR-o',
    appId: '1:758888854246:ios:3d05fa4c9b19fac2dd0127',
    messagingSenderId: '758888854246',
    projectId: 'cyphlab',
    storageBucket: 'cyphlab.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0dTo66Ytj4u9EnBFD7yZh8C7al5DbR-o',
    appId: '1:758888854246:ios:3d05fa4c9b19fac2dd0127',
    messagingSenderId: '758888854246',
    projectId: 'cyphlab',
    storageBucket: 'cyphlab.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7OxVUHqfg9Ka1kpM5uGKeiY512Rf48G8',
    appId: '1:758888854246:web:fb04bf8929a5eecbdd0127',
    messagingSenderId: '758888854246',
    projectId: 'cyphlab',
    authDomain: 'cyphlab.firebaseapp.com',
    storageBucket: 'cyphlab.firebasestorage.app',
    measurementId: 'G-LH56L6PH0R',
  );
}